import 'package:dart_frog/dart_frog.dart';

List list_of_goods = [
  {
    'title': 'tiny stuff, black belt with extra shirt',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '734',
    'resellCount': '34',
    'orderCount': '2',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'mens senator wear, cheap and light material',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '14',
    'resellCount': '3k',
    'orderCount': '54',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'vintage shirt, black, round bishop collar',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '287',
    'resellCount': '327k',
    'orderCount': '91',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'long sleeve ankara, straight color playing amapiano',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '999k',
    'resellCount': '742',
    'orderCount': '72',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'stuffed denim, crazy black, filled with shit',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '34',
    'resellCount': '34',
    'orderCount': '2',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'multi colored and striped sweatshirt , black high neck color',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '34',
    'resellCount': '4k',
    'orderCount': '12',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'ronaldos machester united jersey',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '13k',
    'resellCount': '34',
    'orderCount': '2',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'high length gown, single colored shoes with free shirt',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '34',
    'resellCount': '97',
    'orderCount': '2k',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
  {
    'title': 'open day, hiv anouncement shirt, express rights',
    'pictureUrl': 'http://jhiuhoeihoie',
    'content': 'this is the content',
    'preorderCount': '76k',
    'resellCount': '34',
    'orderCount': '22',
    'salesPrice': '12,500',
    'discountedPrice': '10,300',
  },
];

Response onRequest(RequestContext context) {
  // TODO: implement route handler
  return Response.json(body: list_of_goods);
}
